Update for SAM 2.1
SauravMaheshkar/samv2 pull request #10
Opened 2024-12-29 19:06 UTC by drien

This brings in the code changes and configs for the 2.1 updates directly from the original sam2 repo. Everything seems to work as expected with both of the 2 and 2.1 models. I just updated the `variants` to have a version prefix so there aren't breaking changes for users who've already integrated this with the 2.0 version.

I duplicated some of the tests to run with the 2.1 models as well and everything passes with both versions, but I've only done real-world testing using the 2.1 checkpoints.

2024-12-29 19:26 UTC, drien commented
Also I've added in a fix for a mistaken dependency on pytest–since the `download_weights()`  method was imported to the root `util` module, it was then imported when running from `sam2 import load_model`, so installing in an environment without pytest would crash with an ImportError. I've just removed that import and made the tests import directly from `sam2.utils.download`.

Reproduce:
```
$ docker run --rm -it python:3.11-bullseye  bash -il
# pip install samv2
...
# python
>>> from sam2 import load_model

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/sam2/__init__.py", line 9, in <module>
    from .build_sam import load_model
  File "/usr/local/lib/python3.11/site-packages/sam2/build_sam.py", line 14, in <module>
    from .utils.misc import VARIANTS, variant_to_config_mapping
  File "/usr/local/lib/python3.11/site-packages/sam2/utils/__init__.py", line 7, in <module>
    from .download import download_weights
  File "/usr/local/lib/python3.11/site-packages/sam2/utils/download.py", line 5, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

Test Fix:
```
$ docker run --rm -it -v .:/opt/samv2 python:3.11-bullseye  bash -il
# pip install -e .
...
# python
>>> from sam2 import load_model
>>> 
>>> exit()
# pip3 install pytest
...
# pytest
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.11.11, pytest-8.3.4, pluggy-1.5.0
rootdir: /opt/samv2
configfile: pyproject.toml
testpaths: tests
plugins: hydra-core-1.3.2
collected 15 items                                                                                                                                                                                         

tests/test_build_model.py ..^C
```

2025-01-02 17:56 UTC, SauravMaheshkar commented on sam2/modeling/sam2_utils.py
Are these new functions used somewhere? This fork was created with the aim to be a minimal version of the original codebase.

2025-01-02 17:58 UTC, SauravMaheshkar commented on sam2/modeling/sam/transformer.py
> -        with torch.nn.attention.sdpa_kernel(get_sdp_backends(dropout_p)):
Any particular reason for removing this ? I created the `get_sdp_backends` function to support the newer backends if available on the system being used.

2025-01-02 17:59 UTC, SauravMaheshkar commented on sam2/modeling/memory_encoder.py
Huh this is interesting, I used `ruff` initially for sorting imports, it shouldn't re-organise like this.

2025-01-02 18:01 UTC, SauravMaheshkar commented on sam2/modeling/sam2_base.py
> +        self.hidden_dim = image_encoder.neck.d_model
maybe I'm being pedantic but just to confirm, this runs okay during forward inference? I don't see a `.neck` submodule.

2025-01-02 18:02 UTC, SauravMaheshkar requested changes
Hey @drien thanks a lot for contributing ❤️ . Left a couple of review notes ☕

2025-02-07 03:14 UTC, SauravMaheshkar commented
Hey @drien, seems like #13 should be fixed by this. Gentle ping on the comments.

2025-02-07 14:18 UTC, drien commented
Hey @SauravMaheshkar, sorry I haven't had time to get back to this—will try to take a look through your comments this weekend. 

Admittedly I started this process by trying to re-play the changes from the source repo onto the files here individually, reviewing how they'd diverged, but that proved pretty time consuming so I just started copying the updated files verbatim from the source repo and running the tests. The tests did pass for me (and I have this running successfully with real world images in a proof of concept application), though it looks like they got stuck on the `isort` step. I can clean that up as well.

2025-02-27 18:51 UTC, SauravMaheshkar commented
Gentle bump @drien

2025-03-06 06:58 UTC, hanialnahas commented
hey @drien, Just a gentle reminder to check the status of the merge request

2026-04-14 10:08 UTC, closed without merging